# Pre-commit configuration for musiclist project
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use the ref you'd like to point at
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py39]
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you'd like to point at
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: check-yaml
      - id: check-added-large-files 